export const glitchTexts = [
  "INITIALIZING SYSTEM...",
  "LOADING NEURAL PATHWAYS...",
  "ESTABLISHING CONNECTION...",
  "ACCESSING MAINFRAME...",
  "DECRYPTING DATA STREAMS...",
  "SYNCHRONIZING PROTOCOLS...",
  "NETWORK AUTHENTICATED",
  "WELCOME TO THE GRID",
]

export const statusMessages = [
  "> SYSTEM BOOT SEQUENCE INITIATED",
  "> LOADING CORE MODULES... [OK]",
  "> ESTABLISHING SECURE CONNECTION... [OK]",
  "> NEURAL NETWORK ONLINE... [OK]",
  "> ALL SYSTEMS OPERATIONAL",
  "> READY FOR USER INPUT",
]
